[package]
name = "orthrus"
version = "1.0.0"
authors = ["Safin Singh <safinsingh.dev@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.34"
dotenv = "0.15.0"
rocket = "0.4.6"
serde = { version = "1.0.117", features = ["derive"] }
